### ISSUE TITLE
Bug in substraction

### ISSUE THREAD

**Issue by Jdash99** [badmetacoder/calculator#1]
./python simplecalculator.py -s "2 - 2"
result: 4.0
it should be: 0.0

Lines 98-99 in simple.py

```
        elif self.op == '-':
            self.r1 = self.r1 + self.r2
```

Needs to be changed to:

```
        elif self.op == '-':
            self.r1 = self.r1 - self.r2
```

Yay!! my first contribution to open source.

**Comment by badmetacoder** [comment]
Fixed. Thank you!
